name: EffiSeg
channels:
  - conda-forge
  - defaults

dependencies:
  # Python environment
  - python=3.8
  - pip
  
  # CUDA support
  - # cudatoolkit # =11.8
  
  # Basic libraries
  - numpy
  - pillow
  - matplotlib
  
  # Pip packages
  - pip:
    # Note: PyTorch CUDA versions will be installed separately
    
    # MMSegmentation ecosystem
    - mmcv==1.5.0
    - mmengine==0.10.7
    - mmsegmentation==0.20.2
    
    # Hugging Face
    - transformers==4.46.3
    - huggingface-hub==0.31.2
    - accelerate==1.0.1
    
    # Computer Vision
    - opencv-python==4.11.0.86
    - timm==1.0.15
    
    # Data Processing
    - numpy==1.24.4
    - pandas==2.0.3
    
    # Visualization & Monitoring
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - wandb==0.19.11
    
    # Utilities
    - tqdm==4.65.2
    - pyyaml==6.0.2
    - requests==2.28.2